apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers: 
        - name: tasks
          image: olonyl/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: user-data-store-env
                  key: AUTH_ADDRESS
            - name: TASKS_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: user-data-store-env
                  key: TASKS_FOLDER
