apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers: 
        - name: users
          image: olonyl/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: user-data-store-env
                  key: AUTH_ADDRESS
